const escaleSprite = 0.3
const posSprite = [400,400]
const textTitle = "Emaster programación básica"
const force = 1000
const angleSprite = 100
const isJumpingSprite = false 
const isRotateSprite = false
const SPEED = 500
let isMove = false
let isGravity = false